---
title: "Vulnerability Analysis for Protected Species & Marine Development"
author: "Joshua Hatch"
date: '`r Sys.Date()`'
site: bookdown::bookdown_site
output:
  bookdown::bs4_book:
    repo:
      base: https://github.com/jmhatch-NOAA/PEMAD-MDEB-VA_ProtSpp
      branch: main
      subdir: bookdown
documentclass: krantz
monofont: "Source Code Pro"
monofontoptions: "Scale=0.7"
link-citations: yes
colorlinks: yes
graphics: yes
description: "Identify what protected species may be most vulnerable to marine development."
github-repo: jmhatch-NOAA/PEMAD-MDEB-VA_ProtSpp
rmd_files: ["index.Rmd", "01-IPFs.Rmd", "02-narw.Rmd"]
---

# Introduction

The increasing demand for renewable energy is driving offshore wind (OSW) development in the United States (US) at an unprecedented rate. The US has a target to reach 30 GW by 2030, with an additional 15 GW from floating substructures by 2035, and aims to produce at least 110 GW by 2050.

However, OSW development in the US Greater Atlantic Region (GAR) coincides with significant proportions of marine mammal and sea turtle populations, with impacts from OSW farms being a major concern. In order to better identify and prioritize vulnerabilities of marine wildlife (i.e., marine mammals and sea turtles) to OSW development, a vulnerability assessment will be undertaken.

## Vulnerability assessment

An OSW Vulnerability Assessment (OSWVA) will be designed in a similar way to previous Climate Vulnerability Assessments (CVAs) using an expert-based scoring approach ([Hare et al. 2016](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0146756); [Lettrich et al. 2023](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0290643); Lettrich et al. *In progress*). Experts will be asked to score multiple features for two separate components: 1) overlap or exposure to factors related to OSW development (i.e., exposure factors) and 2) sensitivity to those exposure factors re: biological attributes. The expert scores for the two separate components will then be tallied and combined into an OSW vulnerability indicator.

The steps:

1.  Scoping and planning
    1.  Define study area
    2.  Identify species to include
    3.  Define OSW exposure factors
        1.  Factors measuring physical change in the environment re: OSW development that could impact marine wildlife
            -   Scoring
    4.  Define sensitivity attributes
        1.  Biological traits that indicate the ability of marine wildlife to respond to the OSW exposure factors
            -   Scoring
2.  Assessment preparation
    1.  Species narratives
    2.  Adaptive capacity
    3.  Data quality

## Scoping and planning

### Define study area

```{r, echo = FALSE, warning = FALSE, results = 'asis'}
# load libraries
library(leaflet)

# data
sne = '../data/sne_region.gpkg' |>
  sf::st_read(quiet = TRUE)
mari = '../data/mari_weas.gpkg' |>
  sf::st_read(quiet = TRUE)

# add data
map = leaflet(width = '100%') |>
  addTiles() |>
  addPolygons(data = sne, fillColor = 'transparent', color = 'black', popup = ~REGION) |>
  addPolygons(data = mari, popup = ~WEA)
map
```

### Species to include

-   [North Atlantic right whale](#north-atlantic-right-whale)
-   Humpback whale
-   Harbor porpoise
-   Grey seal
-   Leatherback turtle

### Define exposures and sensitivities

| Exposure               | Sensitivity                                                         | Rationale                                                                                            |
|-------------------|----------------------------------|-------------------|
| Noise (sound)          | Ability to detect (hearing) and respond to the acoustic environment | Marine wildlife are susceptible to negative effects of man-made noise generated from OSW development |
| Oceanographic effects  |                                                                     |                                                                                                      |
| Vessels                |                                                                     |                                                                                                      |
| Presence of Structures |                                                                     |                                                                                                      |

: **Table**: List of exposure factors and sensitivity attributes considered in the OSWVA for marine wildlife.
