# build Bookdown
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: build-book
jobs:
  build-book:
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install bookdown
        run: |
          install.packages(c("downlit", "xml2"))
        shell: Rscript {0}

      - name: Build book
        run: |
          setwd("bookdown")
          bookdown::render_book("index.Rmd", "all")
        shell: Rscript {0}

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: _book # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
